server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:5366/mall_db
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
